# Generated by Django 4.1.13 on 2024-10-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_allergie_description_allergie_gravite'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='budget_hebdomadaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='preference',
            name='restriction_alimentaire',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
