# Generated by Django 4.1.13 on 2024-10-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_preference_budget_hebdomadaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='budget_hebdomadaire',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='restriction_alimentaire',
        ),
    ]
