# Generated by Django 4.1.13 on 2024-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recettes', '0001_initial'),
        ('liste_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listecourses',
            name='articles',
            field=models.ManyToManyField(through='liste_courses.ArticleCourses', to='recettes.ingredient'),
        ),
    ]
