# Generated by Django 4.1.13 on 2024-09-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recettes', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='cree_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateur'),
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.ManyToManyField(related_name='recettes', through='recettes.IngredientRecette', to='recettes.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientrecette',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientrecette',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recette'),
        ),
    ]
