# Generated by Django 4.1.13 on 2024-09-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='categorie',
            field=models.CharField(default='déjeuner', max_length=50),
        ),
        migrations.AddField(
            model_name='recette',
            name='vegetarien',
            field=models.BooleanField(default=False),
        ),
    ]
