# Generated by Django 4.1.13 on 2024-09-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0003_recette_categorie_recette_vegetarien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='titre',
            new_name='nom',
        ),
    ]
