# Generated by Django 4.1.13 on 2024-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_alter_recette_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
