# Generated by Django 4.1.13 on 2024-10-19 04:58

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0007_alter_recette_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='ingredientrecette',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='recette',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientrecette',
            unique_together={('recette', 'ingredient')},
        ),
        migrations.RemoveField(
            model_name='ingredientrecette',
            name='id',
        ),
        migrations.CreateModel(
            name='RecetteIngredientRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.ingredient')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recette')),
            ],
            options={
                'unique_together': {('recette', 'ingredient')},
            },
        ),
    ]
