# Generated by Django 4.1.13 on 2024-10-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0008_remove_ingredient_id_remove_recette_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientrecette',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recette',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='ingredientrecette',
            name='ingredient',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='ingredientrecette',
            name='recette',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='recette',
            name='categorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recette',
            name='cree_par',
            field=models.CharField(max_length=24),
        ),
        migrations.DeleteModel(
            name='RecetteIngredientRelation',
        ),
    ]
