# Generated by Django 4.1.13 on 2024-10-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0009_alter_ingredientrecette_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='image_url',
        ),
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
