# Generated by Django 4.1.13 on 2024-10-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0010_remove_recette_image_url_recette_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='cree_par',
        ),
    ]
