# Generated by Django 4.1.13 on 2024-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_repas', models.CharField(choices=[('Petit-déjeuner', 'Petit-déjeuner'), ('Déjeuner', 'Déjeuner'), ('Dîner', 'Dîner')], max_length=50)),
            ],
        ),
    ]
