# Generated by Django 4.1.13 on 2024-09-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recettes', '0001_initial'),
        ('plan_repas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repas',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.recette'),
        ),
    ]
