# Generated by Django 4.1.13 on 2024-09-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_repas', '0002_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repas',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateur'),
        ),
        migrations.AddField(
            model_name='planrepas',
            name='repas',
            field=models.ManyToManyField(to='plan_repas.repas'),
        ),
        migrations.AddField(
            model_name='planrepas',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateur'),
        ),
    ]
